---
# create ender user for ansible tasks

# create user
- name: Create user ender
  ansible.builtin.user:
    append: true
    name: ender
    comment: "enders game is ansible"
    createhome: true
    uid: 901
    move_home: true
    home: /home/ender
    shell: /bin/bash
    groups: sudo
  when: ansible_distribution == "Debian"

- name: Create user ender
  ansible.builtin.user:
    append: true
    name: ender
    comment: "enders game is ansible"
    createhome: true
    uid: 901
    move_home: true
    home: /home/ender
    shell: /bin/bash
    groups: wheel
  when: ansible_distribution == "Fedora"

# add ssh key
- name: Ssh key
  ansible.posix.authorized_key:
    user: ender
    key: "{{ lookup('file', 'ender_rsa.pub') }}"

# allow sudo without password
- name: Create sudoers.d file
  ansible.builtin.lineinfile:
    dest: /etc/sudoers.d/ender
    line: 'ender ALL=(ALL) NOPASSWD: ALL'
    create: true
    mode: 0440

# verify this exists in sudoers
- name: Includedir within sudoers file
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    line: "#includedir /etc/sudoers.d"
