---
- name: Create swapfile
  ansible.builtin.command: >
    dd if=/dev/zero of={{ swapfile_location }}
    bs=1MB count={{ swapfile_size }}
  args:
    creates: "{{ swapfile_location }}"
  notify: Make-start-swap

- name: Set swapfile permissions
  ansible.builtin.file:
    path: "{{ swapfile_location }}"
    mode: 0600

- name: Mount swapfile
  ansible.posix.mount:
    state: present
    src: "{{ swapfile_location }}"
    name: swap
    fstype: swap
    dump: 0
    passno: 0
    opts: defaults
