---
- name: Debian DNS tasks
  ansible.builtin.include_tasks: debian.yml
  when: ansible_distribution == "Debian"

- name: Fedora DNS tasks
  ansible.builtin.include_tasks: fedora.yml
  when: ansible_distribution == "Fedora"
