- name: Install postfix
  ansible.builtin.yum:
    name: postfix
    state: present

- name: Template postfix config
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/postfix/"
    mode: '0644'
  with_items:
    - "master.cf"
    - "main.cf"
  notify: Restart postfix
  tags:
    - mailupdate

- name: Copy postfix files over
  ansible.builtin.copy:
    src: etc/
    dest: /etc/
    mode: '0644'
  notify: Restart postfix
  tags:
    - mailupdate

- name: Rebuild postfix alias maps
  ansible.builtin.command: postmap /etc/postfix/alias_map-{{ item }}
  with_items: "{{ hosted_domains }}"
  tags:
    - mailupdate
  # to make ansible lint happy, will always report "changed"
  register: postmap
  changed_when: postmap.rc == 0

- name: Rebuild postfix mailbox maps
  ansible.builtin.command: postmap /etc/postfix/mailbox_map-{{ item }}
  with_items: "{{ hosted_domains }}"
  tags:
    - mailupdate
  # to make ansible lint happy, will always report "changed"
  register: postmap
  changed_when: postmap.rc == 0

- name: Run newaliases
  ansible.builtin.command: newaliases
  tags:
    - mailupdate
  # to make ansible lint happy, will always report "changed"
  register: newaliases
  changed_when: newaliases.rc == 0

- name: Start enable postfix
  ansible.builtin.service:
    name: postfix
    state: started
    enabled: true

- name: Reload postfix once a day to pick up ssl certs
  ansible.builtin.cron:
    special_time: daily
    name: postfix-reload
    user: root
    job: systemctl reload postfix
