---
- name: Set the hostname
  ansible.builtin.hostname:
    name: "{{ hostname | default(inventory_hostname) | default('unset') }}"
  tags: set_hostname

- name: Remove unattended upgrades
  ansible.builtin.package:
    name: unattended-upgrades
    state: absent
  when: ansible_distribution_file_variety == "Debian"

- name: Remove sendmail
  ansible.builtin.package:
    name: sendmail
    state: absent

- name: Add epel to system
  ansible.builtin.package:
    name: epel-release
    state: present
  when: ansible_distribution == "Fedora"

- name: Install packages
  ansible.builtin.package:
    state: present
    name:
      - sudo
      - lsof
      - rsyslog
      - rsync
      - cpanminus   # why need this?:wq
      - tmux
      - htop
      #- cronie
      #- perl-App-cpanminus

- name: Start and enable rsyslog
  ansible.builtin.service:
    name: rsyslog
    enabled: yes
    state: started

- name: Add compression to logrotate
  ansible.builtin.lineinfile:
    path: /etc/logrotate.conf
    regexp: '^compress'
    line: compress
  tags: logrotate

- name: Enable logrotate
  ansible.builtin.systemd:
    name: logrotate.timer
    state: started
    enabled: true
  tags: logrotate

- name: Start enable cron daemon
  ansible.builtin.service:
    #name: crond
    name: cron
    state: started
    enabled: true
